"""empty message

Revision ID: 368e535d00cc
Revises: 
Create Date: 2019-05-29 15:26:38.790677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368e535d00cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
